using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using RegulatoryComplianceApplication.Core.Interfaces;
using RegulatoryComplianceApplication.Core.Models;
using ClosedXML.Excel;
using System.IO;

namespace RegulatoryComplianceApplication.Infrastructure.Services
{
    public class ReportService : IReportService
    {
        public async Task<byte[]> GenerateDocumentsPdfAsync(
            List<DocumentReportRow> documents,
            int validCount,
            int expiringSoonCount,
            int expiredCount)
        {
            QuestPDF.Settings.License = LicenseType.Community;

            var complianceRate = documents.Count == 0
            ? 0
            : (double)validCount / documents.Count * 100;

            var pdf = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(30);

                    page.Header().Column(header =>
                    {
                        header.Item()
                            .Background(Colors.Blue.Darken2)
                            .Padding(15)
                            .Text("REGULATORY COMPLIANCE REPORT")
                            .FontColor(Colors.White)
                            .FontSize(22)
                            .Bold()
                            .AlignCenter();

                        header.Item().PaddingTop(10);

                        header.Item().Row(row =>
                        {
                            row.RelativeItem().Text($"Generated: {DateTime.Now:dd MMM yyyy HH:mm}");

                            row.RelativeItem()
                                .AlignRight()
                                .Text("Generated by: Regulatory Compliance System");
                        });

                        header.Item().PaddingBottom(15);
                    });

                    page.Content().Column(column =>
                    {
                        column.Item()
                            .Background(Colors.Grey.Lighten3)
                            .Padding(10)
                            .Column(summary =>
                            {
                                summary.Item()
                                    .Text("EXECUTIVE SUMMARY")
                                    .Bold()
                                    .FontSize(16);

                                summary.Item().PaddingTop(10);

                                summary.Item().Text($"Total Documents: {documents.Count}");

                                summary.Item().Text($"Valid Documents: {validCount}");

                                summary.Item().Text($"Expiring Soon: {expiringSoonCount}");

                                summary.Item().Text($"Expired Documents: {expiredCount}");

                                summary.Item().Text($"Compliance Rate: {complianceRate:F1}%");
                            });

                        column.Item().PaddingVertical(20);

                        column.Item().PaddingVertical(10);

                        column.Item()
                            .Text("DOCUMENT DETAILS")
                            .FontSize(16)
                            .Bold();

                        column.Item().PaddingBottom(10);

                        column.Item().Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(3);
                                columns.RelativeColumn(2);
                                columns.RelativeColumn(3);
                                columns.RelativeColumn(2);
                                columns.RelativeColumn(2);
                            });

                            table.Header(header =>
                            {
                                header.Cell().Background(Colors.Blue.Darken2).Padding(6)
                                    .Text("Title").FontColor(Colors.White).Bold();

                                header.Cell().Background(Colors.Blue.Darken2).Padding(6)
                                    .Text("Number").FontColor(Colors.White).Bold();

                                header.Cell().Background(Colors.Blue.Darken2).Padding(6)
                                    .Text("Responsible").FontColor(Colors.White).Bold();

                                header.Cell().Background(Colors.Blue.Darken2).Padding(6)
                                    .Text("Expiry").FontColor(Colors.White).Bold();

                                header.Cell().Background(Colors.Blue.Darken2).Padding(6)
                                    .Text("Status").FontColor(Colors.White).Bold();
                            });

                            foreach (var document in documents)
                            {
                                table.Cell()
                                    .PaddingVertical(4)
                                    .Text(document.Title);

                                table.Cell()
                                    .PaddingVertical(4)
                                    .Text(document.DocumentNumber);

                                table.Cell()
                                    .PaddingVertical(4)
                                    .Text(document.ResponsibleUser);

                                table.Cell()
                                    .PaddingVertical(4)
                                    .Text(document.ExpiryDate?.ToString("dd MMM yyyy") ?? "-");

                                var statusColor = Colors.Black;

                                if (document.Status == "Valid")
                                    statusColor = Colors.Green.Darken2;
                                else if (document.Status == "Expiring Soon")
                                    statusColor = Colors.Orange.Darken2;
                                else if (document.Status == "Expired")
                                    statusColor = Colors.Red.Darken2;

                                table.Cell()
                                    .PaddingVertical(4)
                                    .Text(document.Status)
                                    .FontColor(statusColor)
                                    .Bold();
                            }
                        });
                    });

                    page.Footer().Row(row =>
                    {
                        row.RelativeItem()
                            .Text("Generated by Regulatory Compliance System")
                            .FontSize(10);

                        row.ConstantItem(80)
                            .AlignRight()
                            .Text(text =>
                            {
                                text.CurrentPageNumber();
                                text.Span(" / ");
                                text.TotalPages();
                            });
                    });
                });
            });

            return await Task.FromResult(pdf.GeneratePdf());
        }
        public async Task<byte[]> GenerateDocumentsExcelAsync(
    List<DocumentReportRow> documents)
        {
            using var workbook = new XLWorkbook();

            var worksheet = workbook.Worksheets.Add("Documents Report");

            worksheet.Cell(1, 1).Value = "Title";
            worksheet.Cell(1, 2).Value = "Document Number";
            worksheet.Cell(1, 3).Value = "Responsible User";
            worksheet.Cell(1, 4).Value = "Expiry Date";
            worksheet.Cell(1, 5).Value = "Status";

            var header = worksheet.Range(1, 1, 1, 5);

            header.Style.Font.Bold = true;
            header.Style.Fill.BackgroundColor = XLColor.LightBlue;

            int row = 2;

            foreach (var document in documents)
            {
                worksheet.Cell(row, 1).Value = document.Title;
                worksheet.Cell(row, 2).Value = document.DocumentNumber;
                worksheet.Cell(row, 3).Value = document.ResponsibleUser;
                worksheet.Cell(row, 4).Value =
                    document.ExpiryDate?.ToString("dd MMM yyyy");
                worksheet.Cell(row, 5).Value = document.Status;

                row++;
            }

            worksheet.Columns().AdjustToContents();

            using var stream = new MemoryStream();

            workbook.SaveAs(stream);

            return await Task.FromResult(stream.ToArray());
        }
        public async Task<byte[]> GenerateBillsPdfAsync(
    List<BillReportRow> bills,
    int paidCount,
    int pendingCount,
    int overdueCount)
        {
            QuestPDF.Settings.License = LicenseType.Community;

            var paymentRate = bills.Count == 0
                ? 0
                : (double)paidCount / bills.Count * 100;

            var pdf = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(30);

                    page.Header().Column(header =>
                    {
                        header.Item()
                            .Background(Colors.Blue.Darken2)
                            .Padding(15)
                            .Text("BILLS REPORT")
                            .FontColor(Colors.White)
                            .FontSize(22)
                            .Bold()
                            .AlignCenter();

                        header.Item().PaddingTop(10);

                        header.Item().Row(row =>
                        {
                            row.RelativeItem()
                                .Text($"Generated: {DateTime.Now:dd MMM yyyy HH:mm}");

                            row.RelativeItem()
                                .AlignRight()
                                .Text("Generated by: Regulatory Compliance System");
                        });

                        header.Item().PaddingBottom(15);
                    });

                    page.Content().Column(column =>
                    {
                        column.Item()
                            .Background(Colors.Grey.Lighten3)
                            .Padding(10)
                            .Column(summary =>
                            {
                                summary.Item()
                                    .Text("EXECUTIVE SUMMARY")
                                    .Bold()
                                    .FontSize(16);

                                summary.Item().PaddingTop(10);

                                summary.Item().Text($"Total Bills: {bills.Count}");

                                summary.Item().Text($"Paid Bills: {paidCount}");

                                summary.Item().Text($"Pending Bills: {pendingCount}");

                                summary.Item().Text($"Overdue Bills: {overdueCount}");

                                summary.Item().Text($"Payment Rate: {paymentRate:F1}%");
                            });

                        column.Item().PaddingVertical(20);

                        column.Item()
                            .Text("BILL DETAILS")
                            .Bold()
                            .FontSize(16);

                        column.Item().PaddingBottom(10);

                        column.Item().Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(3);
                                columns.RelativeColumn(2);
                                columns.RelativeColumn(3);
                                columns.RelativeColumn(2);
                                columns.RelativeColumn(2);
                                columns.RelativeColumn(2);
                            });

                            table.Header(header =>
                            {
                                header.Cell().Background(Colors.Blue.Darken2).Padding(6)
                                    .Text("Bill").FontColor(Colors.White).Bold();

                                header.Cell().Background(Colors.Blue.Darken2).Padding(6)
                                    .Text("Amount").FontColor(Colors.White).Bold();

                                header.Cell().Background(Colors.Blue.Darken2).Padding(6)
                                    .Text("Assigned User").FontColor(Colors.White).Bold();

                                header.Cell().Background(Colors.Blue.Darken2).Padding(6)
                                    .Text("Due Date").FontColor(Colors.White).Bold();

                                header.Cell().Background(Colors.Blue.Darken2).Padding(6)
                                    .Text("Frequency").FontColor(Colors.White).Bold();

                                header.Cell().Background(Colors.Blue.Darken2).Padding(6)
                                    .Text("Status").FontColor(Colors.White).Bold();
                            });

                            foreach (var bill in bills)
                            {
                                table.Cell().PaddingVertical(4)
                                    .Text(bill.BillName);

                                table.Cell().PaddingVertical(4)
                                    .Text($"{bill.Amount:N2} SAR");

                                table.Cell().PaddingVertical(4)
                                    .Text(bill.AssignedUser);

                                table.Cell().PaddingVertical(4)
                                    .Text(bill.DueDate.ToString("dd MMM yyyy"));

                                table.Cell().PaddingVertical(4)
                                    .Text(bill.Frequency);

                                var statusColor = Colors.Black;

                                if (bill.Status == "Paid")
                                    statusColor = Colors.Green.Darken2;
                                else if (bill.Status == "Pending")
                                    statusColor = Colors.Orange.Darken2;
                                else if (bill.Status == "Overdue")
                                    statusColor = Colors.Red.Darken2;

                                table.Cell()
                                    .PaddingVertical(4)
                                    .Text(bill.Status)
                                    .FontColor(statusColor)
                                    .Bold();
                            }
                        });
                    });

                    page.Footer().Row(row =>
                    {
                        row.RelativeItem()
                            .Text("Generated by Regulatory Compliance System")
                            .FontSize(10);

                        row.ConstantItem(80)
                            .AlignRight()
                            .Text(text =>
                            {
                                text.CurrentPageNumber();
                                text.Span(" / ");
                                text.TotalPages();
                            });
                    });
                });
            });

            return await Task.FromResult(pdf.GeneratePdf());
        }
        public async Task<byte[]> GenerateBillsExcelAsync(
    List<BillReportRow> bills)
        {
            using var workbook = new XLWorkbook();

            var worksheet = workbook.Worksheets.Add("Bills Report");

            worksheet.Cell(1, 1).Value = "Bill Name";
            worksheet.Cell(1, 2).Value = "Amount";
            worksheet.Cell(1, 3).Value = "Assigned User";
            worksheet.Cell(1, 4).Value = "Due Date";
            worksheet.Cell(1, 5).Value = "Frequency";
            worksheet.Cell(1, 6).Value = "Status";

            var header = worksheet.Range(1, 1, 1, 6);

            header.Style.Font.Bold = true;
            header.Style.Fill.BackgroundColor = XLColor.LightBlue;

            int row = 2;

            foreach (var bill in bills)
            {
                worksheet.Cell(row, 1).Value = bill.BillName;
                worksheet.Cell(row, 2).Value = bill.Amount;
                worksheet.Cell(row, 2).Style.NumberFormat.Format = "#,##0.00 \"SAR\"";

                worksheet.Cell(row, 3).Value = bill.AssignedUser;
                worksheet.Cell(row, 4).Value = bill.DueDate.ToString("dd MMM yyyy");
                worksheet.Cell(row, 5).Value = bill.Frequency;
                worksheet.Cell(row, 6).Value = bill.Status;

                row++;
            }

            worksheet.Columns().AdjustToContents();

            using var stream = new MemoryStream();

            workbook.SaveAs(stream);

            return await Task.FromResult(stream.ToArray());
        }
    }
}