using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using RegulatoryComplianceApplication.Core.Interfaces;
using RegulatoryComplianceApplication.Core.Models;

namespace RegulatoryComplianceApplication.Infrastructure.Services
{
    public class ReportService : IReportService
    {
        public async Task<byte[]> GenerateDocumentsPdfAsync(
            List<DocumentReportRow> documents,
            int validCount,
            int expiringSoonCount,
            int expiredCount)
        {
            QuestPDF.Settings.License = LicenseType.Community;

            var complianceRate = documents.Count == 0
            ? 0
            : (double)validCount / documents.Count * 100;

            var pdf = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(30);

                    page.Header().Column(header =>
                    {
                        header.Item()
                            .Background(Colors.Blue.Darken2)
                            .Padding(15)
                            .Text("REGULATORY COMPLIANCE REPORT")
                            .FontColor(Colors.White)
                            .FontSize(22)
                            .Bold()
                            .AlignCenter();

                        header.Item().PaddingTop(10);

                        header.Item().Row(row =>
                        {
                            row.RelativeItem().Text($"Generated: {DateTime.Now:dd MMM yyyy HH:mm}");

                            row.RelativeItem()
                                .AlignRight()
                                .Text("Generated by: Regulatory Compliance System");
                        });

                        header.Item().PaddingBottom(15);
                    });

                    page.Content().Column(column =>
                    {
                        column.Item()
                            .Background(Colors.Grey.Lighten3)
                            .Padding(10)
                            .Column(summary =>
                            {
                                summary.Item()
                                    .Text("EXECUTIVE SUMMARY")
                                    .Bold()
                                    .FontSize(16);

                                summary.Item().PaddingTop(10);

                                summary.Item().Text($"Total Documents: {documents.Count}");

                                summary.Item().Text($"Valid Documents: {validCount}");

                                summary.Item().Text($"Expiring Soon: {expiringSoonCount}");

                                summary.Item().Text($"Expired Documents: {expiredCount}");

                                summary.Item().Text($"Compliance Rate: {complianceRate:F1}%");
                            });

                        column.Item().PaddingVertical(20);

                        column.Item().PaddingVertical(10);

                        column.Item()
                            .Text("DOCUMENT DETAILS")
                            .FontSize(16)
                            .Bold();

                        column.Item().PaddingBottom(10);

                        column.Item().Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(3);
                                columns.RelativeColumn(2);
                                columns.RelativeColumn(3);
                                columns.RelativeColumn(2);
                                columns.RelativeColumn(2);
                            });

                            table.Header(header =>
                            {
                                header.Cell().Text("Title").Bold();
                                header.Cell().Text("Number").Bold();
                                header.Cell().Text("Responsible").Bold();
                                header.Cell().Text("Expiry").Bold();
                                header.Cell().Text("Status").Bold();
                            });

                            foreach (var document in documents)
                            {
                                table.Cell().Text(document.Title);
                                table.Cell().Text(document.DocumentNumber);
                                table.Cell().Text(document.ResponsibleUser);
                                table.Cell().Text(document.ExpiryDate?.ToString("dd MMM yyyy") ?? "-");
                                table.Cell().Text(document.Status);
                            }
                        });
                    });

                    page.Footer()
                        .AlignCenter()
                        .Text(x =>
                        {
                            x.Span("Generated by Regulatory Compliance System");
                        });
                });
            });

            return await Task.FromResult(pdf.GeneratePdf());
        }
    }
}